name: Sync Notion Content

on:
  schedule:
    # 매일 오전 9시 (KST 기준, UTC+9)에 실행
    - cron: '0 0 * * *'  
  workflow_dispatch:  # 수동 실행 가능

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run Notion sync
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        NOTION_STORIES_DATABASE_ID: ${{ secrets.NOTION_STORIES_DATABASE_ID }}
        NOTION_FIGURES_DATABASE_ID: ${{ secrets.NOTION_FIGURES_DATABASE_ID }}
      run: npm run sync:notion
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🔄 Auto-sync: Update content from Notion $(date '+%Y-%m-%d %H:%M')"
          git push
        fi